apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/296241930FEC0B2E6734A348B40FE67F